### ISSUE TITLE
Issues configuring

### ISSUE THREAD

**Issue by BeowolfSchaefer** [mmertama/Qmics#7]
I have been trying to set one of these up and I thought I had everything configured correctly but after I fill out the configuration page and log back in I get the error message "Fatal error: Call to undefined function createUserTable() in /var/www/html/ComicBooks/script/entry.php on line 55"

Any idea what I might be doing wrong here?

**Comment by mmertama** [comment]
Sorry - it looks like I forgot to Sync the last commit. Now I have done it, please pull a new version.

**Comment by BeowolfSchaefer** [comment]
Will do. Thank you sir!
