### ISSUE TITLE
Sailfish Port

### ISSUE THREAD

**Issue by TheNocturnalEvil** [mmertama/Qmics#8]
Can you make this app for SailfishOS too?

**Comment by mmertama** [comment]
The original implementation was on Qt, but then I re-implemented as web app
https://github.com/mmertama/Qmics - It definitely should run on Sailfish's
browser, you just need a host for a server - maybe you can even get the
server running in the Sailfish, I havent tried.


On Sun, Oct 29, 2017 at 11:26 PM, TheNocturnalEvil <notifications@github.com
